version: "3.9"

services:

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    ports: 
      - "5432:5432"


  django:
    build: 
      context: ./docker/django
      dockerfile: Dockerfile
    volumes:
      - ./src/backend:/code/
    ports:
      - "8888:8888"
    environment:
      POSTGRES_NAME: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_HOST: db
    depends_on:
      - db
    tty: true


  front:
    build:
      context: ./docker/nuxt
      dockerfile: Dockerfile
    volumes: 
      - ./src/frontend:/code
    ports: 
      - "3030:3030"
    depends_on:
      - django
    tty: true
